Repository heroku/buildpacks-jvm, pull requests merged in 2021-12, with the labels that each got.

#214 Update to Rust 1.57 in CI
  .circleci/config.yml
Labels: skip changelog

#215 Port heroku/jvm-function-invoker to libcnb 0.4.0
  .circleci/config.yml
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/Cargo.lock
  buildpacks/jvm-function-invoker/Cargo.toml
  buildpacks/jvm-function-invoker/Makefile.toml
  buildpacks/jvm-function-invoker/README.md
  buildpacks/jvm-function-invoker/build.sh
  buildpacks/jvm-function-invoker/buildpack.toml
  buildpacks/jvm-function-invoker/opt/jvm-runtime.sh
  buildpacks/jvm-function-invoker/src/build.rs
  buildpacks/jvm-function-invoker/src/common.rs
  buildpacks/jvm-function-invoker/src/detect.rs
  buildpacks/jvm-function-invoker/src/error.rs
  buildpacks/jvm-function-invoker/src/layers/bundle.rs
  buildpacks/jvm-function-invoker/src/layers/opt.rs
  buildpacks/jvm-function-invoker/src/layers/runtime.rs
  buildpacks/jvm-function-invoker/src/main.rs
  test/meta-buildpacks/java-function/buildpack.toml
Labels: languages-review

#220 Update sf-fx-runtime-java to 1.0.4
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
Labels: languages-review

#221 Update Pack to v0.23.0 in CI
  .circleci/config.yml
Labels: skip changelog

#223 Update heroku/gradle to v36
  shimmed-buildpacks/gradle/CHANGELOG.md
  shimmed-buildpacks/gradle/buildpack.toml
Labels: languages-review

#224 Fix GitHub tarball release scripts
  .github/scripts/release-workflow-package-push.sh
  .github/workflows/release.yml
Labels: skip changelog, languages-review

#226 Fix CNB package file upload
  .github/scripts/release-workflow-package-push.sh
  .github/workflows/release.yml
Labels: skip changelog, languages-review

#227 Fix licenses table in buildpack.toml files
  buildpacks/jvm-function-invoker/buildpack.toml
  buildpacks/jvm/buildpack.toml
  buildpacks/maven/buildpack.toml
  meta-buildpacks/java-function/buildpack.toml
  meta-buildpacks/java/buildpack.toml
  shimmed-buildpacks/clojure/buildpack.toml
  shimmed-buildpacks/gradle/buildpack.toml
  shimmed-buildpacks/scala/buildpack.toml
Labels: skip changelog, languages-review
