Repository heroku/buildpacks-jvm, pull requests merged in 2021-05, with the labels that each got.

#88 Update JVM function invoker to 0.2.0
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
Labels: languages-review

#74 Move integration testing to shared OSS library (Cutlass)
  .rspec
  Gemfile
  Gemfile.lock
  test/rapier/rapier.rb
  test/specs/java/basic_spec.rb
  test/specs/java/spec_helper.rb
  test/specs/maven/customization_spec.rb
  test/specs/maven/misc_spec.rb
  test/specs/maven/polyglot_spec.rb
  test/specs/maven/process_types_spec.rb
  test/specs/maven/settings_xml_spec.rb
  test/specs/maven/spec_helper.rb
  test/specs/maven/version_handling_spec.rb
Labels: skip changelog

#96 remove warning in jvm buildpack, deprecation of version field
  buildpacks/jvm/bin/detect
Labels: skip changelog

#97 Bump sf-fx-runtime-java-runtime to 0.2.1
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
Labels: languages-review, skip changelog

#94 update jvm-function-invoker detect for new project.toml schema changes
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/bin/detect
  buildpacks/jvm-function-invoker/lib/toolbox.sh
Labels: skip changelog

#102 Update sf-fx-runtime-java to 0.2.2
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
Labels: languages-review

#105 Update sf-fx-runtime-java to 0.2.3
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
Labels: languages-review

#109 Update sf-fx-runtime-java to 0.2.4
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
Labels: languages-review
