Repository heroku/buildpacks-jvm, pull requests merged in 2021-07, with the labels that each got.

#113 Update JVM function runtime to 1.0.0
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
  test/meta-buildpacks/java-function/buildpack.toml
Labels: languages-review

#115 Install Rust dependencies during release
  .github/workflows/release.yml
Labels: languages-review, skip changelog

#120 Update OpenJDK default versions
  buildpacks/jvm/CHANGELOG.md
  buildpacks/jvm/lib/jvm.sh
Labels: languages-review

#123 Revert changes from heroku/jvm-function-invoker `0.3.0`
  .circleci/config.yml
  .github/workflows/release.yml
  .gitignore
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/Cargo.lock
  buildpacks/jvm-function-invoker/Cargo.toml
  buildpacks/jvm-function-invoker/Makefile.toml
  buildpacks/jvm-function-invoker/README.md
  buildpacks/jvm-function-invoker/bin/build
  buildpacks/jvm-function-invoker/bin/detect
  buildpacks/jvm-function-invoker/build.sh
  buildpacks/jvm-function-invoker/buildpack.toml
  buildpacks/jvm-function-invoker/common-lib
  buildpacks/jvm-function-invoker/lib/toolbox.sh
  buildpacks/jvm-function-invoker/src/bin/bp_build.rs
  buildpacks/jvm-function-invoker/src/bin/bp_detect.rs
  buildpacks/jvm-function-invoker/src/builder.rs
  buildpacks/jvm-function-invoker/src/data.rs
  buildpacks/jvm-function-invoker/src/data/buildpack_toml.rs
  buildpacks/jvm-function-invoker/src/data/function_bundle.rs
  buildpacks/jvm-function-invoker/src/data/runtime.rs
  buildpacks/jvm-function-invoker/src/lib.rs
  buildpacks/jvm-function-invoker/src/util.rs
  buildpacks/jvm-function-invoker/src/util/logger.rs
Labels: languages-review

#125 Update JVM function runtime to 1.0.0
  buildpacks/jvm-function-invoker/CHANGELOG.md
  buildpacks/jvm-function-invoker/buildpack.toml
  test/meta-buildpacks/java-function/buildpack.toml
Labels: languages-review

#128 Switch ECR registry URLs to use custom registry alias
  buildpacks/jvm-function-invoker/buildpack.toml
  buildpacks/jvm/buildpack.toml
  buildpacks/maven/buildpack.toml
  meta-buildpacks/java-function/buildpack.toml
  meta-buildpacks/java-function/package.toml
  meta-buildpacks/java/buildpack.toml
  meta-buildpacks/java/package.toml
  shimmed-buildpacks/clojure/buildpack.toml
  shimmed-buildpacks/gradle/buildpack.toml
  shimmed-buildpacks/scala/buildpack.toml
Labels: skip changelog

#129 Make publishing script fail if duplicate buildpack IDs found
  .github/scripts/release-workflow-package-push.sh
Labels: skip changelog

#130 Enable Dependabot for GitHub Actions and Cargo
  .github/dependabot.yml
Labels: skip changelog
