Repository heroku/buildpacks-jvm, pull requests merged in 2022-05, with the labels that each got.

#281 Bump to pack 0.26.0
  .circleci/config.yml
Labels: skip changelog

#285 Rename `PUBLIC_REPO_TOKEN` to `CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN`
  .github/workflows/release.yml
Labels: skip changelog

#292 Make Dependabot labels consistent with other repos
  .github/dependabot.yml
  .github/workflows/check_changelog.yml
Labels: skip changelog

#297 Bump Cargo dependencies
  .circleci/config.yml
  Cargo.lock
  buildpacks/jvm-function-invoker/Cargo.toml
  buildpacks/jvm/Cargo.toml
  buildpacks/maven/Cargo.toml
Labels: skip changelog, dependencies

#298 Add OpenJDK Q2 2022 updates
  buildpacks/jvm/CHANGELOG.md
  buildpacks/jvm/src/version.rs
Labels: languages-review
