Repository heroku/buildpacks-jvm, pull requests merged in 2023-06, with the labels that each got.

#516 Adding prepare release workflow automation
  .github/workflows/prepare-release.yml
Labels: skip changelog

#517 Bump all buildpack versions to 1.1.0
  buildpacks/jvm-function-invoker/buildpack.toml
  buildpacks/jvm/buildpack.toml
  buildpacks/maven/buildpack.toml
  buildpacks/sbt/buildpack.toml
  meta-buildpacks/java-function/buildpack.toml
  meta-buildpacks/java/buildpack.toml
  meta-buildpacks/scala/buildpack.toml
Labels: skip changelog, buildpack: heroku/sbt, buildpack: heroku/jvm, buildpack: heroku/maven, buildpack: heroku/jvm-function-invoker, buildpack: heroku/java, buildpack: heroku/java-function, buildpack: heroku/scala

#519 Adding release workflow automation
  .github/workflows/prepare-release.yml
  .github/workflows/release-new.yml
Labels: skip changelog

#521 Fix CHANGELOG.md
  buildpacks/jvm/CHANGELOG.md
Labels: buildpack: heroku/jvm

#524 Fix changelog heading
  meta-buildpacks/java-function/CHANGELOG.md
Labels: buildpack: heroku/java-function

#526 Use libcnb URIs in package.toml files
  meta-buildpacks/java-function/package.toml
  meta-buildpacks/java/package.toml
  meta-buildpacks/scala/package.toml
Labels: skip changelog, buildpack: heroku/java, buildpack: heroku/java-function, buildpack: heroku/scala

#528 Adds all the required credentials for the release workflow
  .github/workflows/release-new.yml
Labels: skip changelog

#529 Removing the strategy from the update builder workflow
  .github/workflows/release-new.yml
Labels: skip changelog

#530 Uses the expanded properties exposed by the detect workflow
  .github/workflows/release-new.yml
Labels: skip changelog

#531 Remove legacy release automation
  .editorconfig
  .github/scripts/release-workflow-package-push.sh
  .github/scripts/release-workflow-prepare-pr.sh
  .github/workflows/release-new.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  buildpacks/jvm-function-invoker/build.sh
  buildpacks/jvm/build.sh
  buildpacks/maven/build.sh
  buildpacks/sbt/build.sh
Labels: skip changelog
