Repository heroku/buildpacks-jvm, pull requests merged in 2023-08, with the labels that each got.

#555 Rename CNB release metadata
  buildpacks/jvm-function-invoker/buildpack.toml
  buildpacks/jvm/buildpack.toml
  buildpacks/maven/buildpack.toml
  buildpacks/sbt/buildpack.toml
  meta-buildpacks/java-function/buildpack.toml
  meta-buildpacks/java/buildpack.toml
  meta-buildpacks/scala/buildpack.toml
Labels: skip changelog

#557 Use stable workflow release
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
Labels: skip changelog

#556 Remove vulnerable Maven versions, add support for 3.9.4
  Cargo.lock
  buildpacks/maven/CHANGELOG.md
  buildpacks/maven/Cargo.toml
  buildpacks/maven/README.md
  buildpacks/maven/buildpack.toml
  buildpacks/maven/src/errors.rs
  buildpacks/maven/src/layer/maven.rs
  buildpacks/maven/src/main.rs
  buildpacks/maven/src/util.rs
  buildpacks/maven/tests/integration/versions.rs
Labels: buildpack: heroku/maven, buildpack: heroku/java

#560 Upgrade to libcnb 0.14.0
  Cargo.lock
  Cargo.toml
  buildpacks/jvm-function-invoker/tests/integration/smoke.rs
  buildpacks/sbt/tests/integration/sbt_at_launch.rs
  shared-test/src/lib.rs
Labels: skip changelog, buildpack: heroku/sbt, buildpack: heroku/jvm, buildpack: heroku/maven, buildpack: heroku/jvm-function-invoker, buildpack: heroku/gradle, buildpack: heroku/java, buildpack: heroku/java-function, buildpack: heroku/scala

#567 Add libcnb-cargo's default output directory to `.gitignore`
  .gitignore
Labels: skip changelog

#566 Set an explicit libcnb dependency version
  Cargo.toml
Labels: skip changelog

#568 Update Procfile CNB to v2.0.1
  buildpacks/sbt/tests/integration/main.rs
  meta-buildpacks/java/CHANGELOG.md
  meta-buildpacks/java/buildpack.toml
  meta-buildpacks/java/package.toml
  meta-buildpacks/scala/CHANGELOG.md
  meta-buildpacks/scala/buildpack.toml
  meta-buildpacks/scala/package.toml
Labels: buildpack: heroku/java, buildpack: heroku/scala
